name: Build release docker images

on:
  push:
    tags: [ release-* ]

jobs:
  build:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write
    env:
      registry: ghcr.io/eddie-energy
    steps:
      - uses: actions/checkout@v4
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Build docker containers
        uses: ./.github/actions/build-containers
        with:
          version: ${{ steps.get_version.outputs.VERSION }}