# See: https://docs.gradle.org/current/userguide/platforms.html#sub:conventional-dependencies-toml
[versions]
spring-boot = "4.0.1"
spring-dependency-management = "1.1.7"
spring-retry = "2.0.4"
spring-oxm = "6.1.5"
spring-security-test = "6.3.3"
junit = "5.10.0"
assertj-core = "3.25.2"
playwright = "1.49.0"
mockito-junit = "5.4.0"
errorprone = "3.0.1"
errorpronecore = "2.23.0"
nullaway = "0.12.14"
jsr305 = "3.0.2"
jaxb = "4.0.2"
jaxb-plugins = "4.0.0"
jakarta-xml-bind = "4.0.0"
rometools = "2.1.0"
jakarta-annotation = "2.1.0"
jakarta-validation = "3.0.2"
jakarta-persistence-api = "3.2.0"
sonar = "7.2.0.6526"
commons-codec = "1.15"
jackson = "3.0.3"
jackson2-short = "2.20"
h2database = "2.3.232"
postgresql = "42.7.3"
javalin = "6.7.0"
jdbi3 = "3.37.1"
reactor = "3.7.0"
slf4j = "2.0.7"
guice = "7.0.0"
jte = "3.1.15"
kafka-clients = "3.4.0"
kafka-streams = "3.9.0"
rabbitmq-amqp-client = "0.3.0"
hibernate-validator = "8.0.1.Final"
hibernate-orm = "7.2.0.Final"
mockwebserver = "4.12.0"
flyway = "11.10.2"
hakky-logcaptor = "2.9.2"
paho-mqtt-client = "1.2.5"
nimbus = "11.10.1"
bouncycastle = "1.78"
keycloak = "25.0.3"
caffeine = "3.2.0"

swagger-annotations = "2.2.34"
openapi-generator = "7.14.0"
jsonschema2pojo = "1.2.2"
openapi-webmvc-ui = "3.0.1"
apache-httpcomponents-version = "4.5.14"
apache-httpcomponents-client-version = "5.4.1"
jackson-databind-nullable-version = "0.2.6"
google-jib = "3.4.0"

testcontainers = "2.0.3"
xmlunit = "2.10.3"

j2mod = "3.2.1"
mvel2 = "2.5.2.Final"

opentelemetry-instrumentation-bom = "2.18.1"

undercouch-download = "5.6.0"

[libraries]
# Static analysis
errorprone-core = { module = "com.google.errorprone:error_prone_core", version.ref = "errorpronecore" }
nullaway = { module = "com.uber.nullaway:nullaway", version.ref = "nullaway" }
jsr305 = { module = "com.google.code.findbugs:jsr305", version.ref = "jsr305" }
## Plugins
errorprone = { module = "net.ltgt.gradle:gradle-errorprone-plugin", version.ref = "errorprone" }
sonar = { module = "org.sonarsource.scanner.gradle:sonarqube-gradle-plugin", version.ref = "sonar" }

# Aggregator artifact of junit5
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-mockito = { module = "org.mockito:mockito-junit-jupiter", version.ref = "mockito-junit" }

# Jackson
jackson-bom = { module = "tools.jackson:jackson-bom", version.ref = "jackson" }
jackson-databind = { module = "tools.jackson.core:jackson-databind", version.ref = "jackson" }
jackson-annotations = { module = "com.fasterxml.jackson.core:jackson-annotations", version.ref = "jackson2-short" }
jackson-jakarta-xmlbind-annotations = { module = "tools.jackson.module:jackson-module-jakarta-xmlbind-annotations", version.ref = "jackson" }
jackson-dataformat-xml = { module = "tools.jackson.dataformat:jackson-dataformat-xml", version.ref = "jackson" }
jackson-dataformat-yaml = { module = "tools.jackson.dataformat:jackson-dataformat-yaml", version.ref = "jackson" }
jackson-core = { module = "tools.jackson.core:jackson-core", version.ref = "jackson" }
jackson-hibernate7 = { module = "tools.jackson.datatype:jackson-datatype-hibernate7", version.ref = "jackson" }

# shared dependencies
testcontainers-postgresql = { module = "org.testcontainers:testcontainers-postgresql", version.ref = "testcontainers" }
testcontainers-toxiproxy = { module = "org.testcontainers:testcontainers-toxiproxy", version.ref = "testcontainers" }
testcontainers-junit = { module = "org.testcontainers:testcontainers-junit-jupiter", version.ref = "testcontainers" }
swagger-annotations = { module = "io.swagger.core.v3:swagger-annotations-jakarta", version.ref = "swagger-annotations" }

# dependencies required by region-connector-at
jaxb-xjc = { module = "org.glassfish.jaxb:jaxb-xjc", version.ref = "jaxb" }
jaxb-runtime = { module = "org.glassfish.jaxb:jaxb-runtime", version.ref = "jaxb" }
jaxb-plugins = { module = "org.jvnet.jaxb:jaxb-plugins", version.ref = "jaxb-plugins" }
jaxb-plugin-annotate = { module = "org.jvnet.jaxb:jaxb-plugin-annotate", version.ref = "jaxb-plugins" }

jakarta-xml-bind-api = { module = "jakarta.xml.bind:jakarta.xml.bind-api", version.ref = "jakarta-xml-bind" }
jakarta-annotation-api = { module = "jakarta.annotation:jakarta.annotation-api", version.ref = "jakarta-annotation" }
jakarta-validation-api = { module = "jakarta.validation:jakarta.validation-api", version.ref = "jakarta-validation" }

reactor-core = { module = "io.projectreactor:reactor-core", version.ref = "reactor" }
reactor-test = { module = "io.projectreactor:reactor-test", version.ref = "reactor" }

commons-codec = { module = "commons-codec:commons-codec", version.ref = "commons-codec" }

xmlunit-core = { module = "org.xmlunit:xmlunit-core", version.ref = "xmlunit" }

# dependencies required by outbound-kafka
kafka-clients = { module = "org.apache.kafka:kafka-clients", version.ref = "kafka-clients" }
testcontainers-kafka = { module = "org.testcontainers:testcontainers-kafka", version.ref = "testcontainers" }

# dpendencies required by outbound-amqp
rabbitmq-amqp-client = { module = "com.rabbitmq.client:amqp-client", version.ref = "rabbitmq-amqp-client" }
testcontainers-rabbitmq = { module = "org.testcontainers:testcontainers-rabbitmq", version.ref = "testcontainers" }

# used by core
postgresql = { module = "org.postgresql:postgresql", version.ref = "postgresql" }
h2database = { module = "com.h2database:h2", version.ref = "h2database" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }

# used by example-app
jte = { module = "gg.jte:jte", version.ref = "jte" }
javalin-rendering = { module = "io.javalin:javalin-rendering", version.ref = "javalin" }
javalin = { module = "io.javalin:javalin", version.ref = "javalin" }
jdbi3-core = { module = "org.jdbi:jdbi3-core", version.ref = "jdbi3" }
guice = { module = "com.google.inject:guice", version.ref = "guice" }
# dependencies required by region-connector-fr
jackson-databind-nullable = { module = "org.openapitools:jackson-databind-nullable", version.ref = "jackson-databind-nullable-version" }
apache-http-client = { module = "org.apache.httpcomponents.client5:httpclient5", version.ref = "apache-httpcomponents-client-version" }
apache-http-mime = { module = "org.apache.httpcomponents:httpmime", version.ref = "apache-httpcomponents-version" }

# Spring Boot
spring-boot-starter-web = { module = "org.springframework.boot:spring-boot-starter-web" }
spring-boot-starter-validation = { module = "org.springframework.boot:spring-boot-starter-validation" }
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test" }
spring-boot-starter-webmvc-test = { module = "org.springframework.boot:spring-boot-starter-webmvc-test" }
spring-boot-starter-webflux-test = { module = "org.springframework.boot:spring-boot-starter-webflux-test" }
spring-boot-starter-restclient-test = { module = "org.springframework.boot:spring-boot-starter-restclient-test" }
spring-boot-starter-flyway = { module = "org.springframework.boot:spring-boot-starter-flyway" }
spring-boot-starter-data-jpa = { module = "org.springframework.boot:spring-boot-starter-data-jpa" }
spring-boot-starter-data-jpa-test = { module = "org.springframework.boot:spring-boot-starter-data-jpa-test" }
spring-boot-starter-webflux = { module = "org.springframework.boot:spring-boot-starter-webflux" }
spring-boot-starter-webclient = { module = "org.springframework.boot:spring-boot-starter-webclient" }
spring-boot-starter-thymeleaf = { module = "org.springframework.boot:spring-boot-starter-thymeleaf" }
spring-boot-starter-actuator = { module = "org.springframework.boot:spring-boot-starter-actuator" }
spring-boot-testcontainers = { module = "org.springframework.boot:spring-boot-testcontainers" }
spring-boot-autoconfigurer = { module = "org.springframework.boot:spring-boot-autoconfigure" }
spring-boot-starter-oauth2-client = { module = "org.springframework.boot:spring-boot-starter-oauth2-client" }
spring-boot-security = { module = "org.springframework.boot:spring-boot-starter-security" }
spring-kafka = { module = "org.springframework.kafka:spring-kafka" }
spring-kafka-test = { module = "org.springframework.kafka:spring-kafka-test" }
spring-retry = { module = "org.springframework.retry:spring-retry", version.ref = "spring-retry" }
spring-openapi-webmvc-ui = { module = "org.springdoc:springdoc-openapi-starter-webmvc-ui", version.ref = "openapi-webmvc-ui" }
spring-oxm = { module = "org.springframework:spring-oxm", version.ref = "spring-oxm" }
spring-security-test = { module = "org.springframework.security:spring-security-test", version.ref = "spring-security-test" }
spring-boot-starter-keycloak = { module = "org.keycloak:keycloak-spring-boot-starter", version.ref = "keycloak" }
spring-boot-starter-oauth2-resource-server = { module = "org.springframework.boot:spring-boot-starter-oauth2-resource-server" }
spring-boot-starter-oauth2-resource-server-test = { module = "org.springframework.boot:spring-boot-starter-security-oauth2-resource-server-test" }
spring-security-oauth-client = { module = "org.springframework.security:spring-security-oauth2-client" }

hibernate-validator = { module = "org.hibernate.validator:hibernate-validator", version.ref = "hibernate-validator" }
hibernate-orm-core = { module = "org.hibernate.orm:hibernate-core", version.ref = "hibernate-orm" }

# extra test dependencies
okhttp3-mockwebserver = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "mockwebserver" }

# Example app
kafka-streams = { module = "org.apache.kafka:kafka-streams", version.ref = "kafka-streams" }
flyway-core = { module = "org.flywaydb:flyway-core", version.ref = "flyway" }
flyway-postgresql = { module = "org.flywaydb:flyway-database-postgresql", version.ref = "flyway" }

# AIIDA
hakky-logcaptor = { module = "io.github.hakky54:logcaptor", version.ref = "hakky-logcaptor" }
eclipse-paho-mqttv5-client = { module = "org.eclipse.paho:org.eclipse.paho.mqttv5.client", version.ref = "paho-mqtt-client" }
j2mod = { module = "com.ghgande:j2mod", version.ref = "j2mod" }
mvel2 = { module = "org.mvel:mvel2", version.ref = "mvel2" }

# Security
nimbus-oidc = { module = "com.nimbusds:oauth2-oidc-sdk", version.ref = "nimbus" }
bouncycastle-bcpkix = { module = "org.bouncycastle:bcpkix-jdk18on", version.ref = "bouncycastle" }
bouncycastle-bcprov = { module = "org.bouncycastle:bcprov-jdk18on", version.ref = "bouncycastle" }

# dependencies required by region-connector-us-green-button
rometools-rome = { module = "com.rometools:rome", version.ref = "rometools" }

# dependencies required by region-connector-cds
caffeine = { module = "com.github.ben-manes.caffeine:caffeine", version.ref = "caffeine" }

# dependencies region-connector-simulation
jakarta-persistence-api = { module = "jakarta.persistence:jakarta.persistence-api", version.ref = "jakarta-persistence-api" }

# dependencies e2e-tests
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj-core" }
playwright = { module = "com.microsoft.playwright:playwright", version.ref = "playwright" }

# Open Telemetry
opentelemetry-instrumentation-bom = { module = "io.opentelemetry.instrumentation:opentelemetry-instrumentation-bom", version.ref = "opentelemetry-instrumentation-bom" }
spring-boot-starter-opentelemetry = { module = "io.opentelemetry.instrumentation:opentelemetry-spring-boot-starter" }
opentelemetry-sdk-metrics = { module = "io.opentelemetry:opentelemetry-sdk-metrics" }
opentelemetry-sdk-testing = { module = "io.opentelemetry:opentelemetry-sdk-testing" }

[bundles]

[plugins]
errorprone = { id = "net.ltgt.errorprone", version.ref = "errorprone" }
# used by example-app
jte-gradle = { id = "gg.jte.gradle", version.ref = "jte" }
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "spring-dependency-management" }
openapi-generator = { id = "org.openapi.generator", version.ref = "openapi-generator" }

# used by metric outbound-connector
jsonschema2pojo = { id = "org.jsonschema2pojo", version.ref = "jsonschema2pojo" }

# AIIDA
google-jib = { id = "com.google.cloud.tools.jib", version.ref = "google-jib" }

## region connecter AT EDA
undercouch-download = { id = "de.undercouch.download", version.ref = "undercouch-download" }
