spring:
  datasource:
    url: jdbc:postgresql://REPLACE_ME:5432/aiida
    username: REPLACE_ME
    password: REPLACE_ME
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: 'true'
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations: 'classpath:db/aiida/migration'

#aiida:
#  datasources:
#    at:
#      oeas:
#      - enabled: false
#        id: REPLACE_ME_1
#        mqtt-server-uri: REPLACE_ME
#        mqtt-subscribe-topic: REPLACE_ME
#        mqtt-username: REPLACE_ME_OR_EMPTY
#        mqtt-password: REPLACE_ME_OR_EMPTY
#      - enabled: false
#        id: REPLACE_ME_2
#        mqtt-server-uri: REPLACE_ME
#        mqtt-subscribe-topic: REPLACE_ME
#        mqtt-username: REPLACE_ME_OR_EMPTY
#        mqtt-password: REPLACE_ME_OR_EMPTY
#    fr:
#      teleinfo:
#      - enabled: false
#        id: REPLACE_ME_1
#        mqtt-server-uri: REPLACE_ME
#        mqtt-subscribe-topic: teleinfo
#        mqtt-username: REPLACE_ME_OR_EMPTY
#        mqtt-password: REPLACE_ME_OR_EMPTY
#        metering-id: REPLACE_ME
#      - enabled: false
#        id: REPLACE_ME_2
#        mqtt-server-uri: REPLACE_ME
#        mqtt-subscribe-topic: teleinfo
#        mqtt-username: REPLACE_ME_OR_EMPTY
#        mqtt-password: REPLACE_ME_OR_EMPTY
#        metering-id: REPLACE_ME
#    sim:
#      simulations:
#        - enabled: true
#          id: 1
#          simulation-period-in-seconds: 5