spring:
  datasource:
    url: jdbc:postgresql://REPLACE_ME:5432/aiida
    username: REPLACE_ME
    password: REPLACE_ME
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: 'true'
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations: 'classpath:db/aiida/migration'
  security:
    oauth2:
      client:
        provider:
          keycloak:
            authorization-uri: ${KEYCLOAK_EXTERNAL_HOST:http://localhost:8888}/realms/${KEYCLOAK_REALM:EDDIE}/protocol/openid-connect/auth
            token-uri: ${KEYCLOAK_INTERNAL_HOST:http://localhost:8888}/realms/${KEYCLOAK_REALM:EDDIE}/protocol/openid-connect/token
            user-info-uri: ${KEYCLOAK_INTERNAL_HOST:http://localhost:8888}/realms/${KEYCLOAK_REALM:EDDIE}/protocol/openid-connect/userinfo
            jwk-set-uri: ${KEYCLOAK_INTERNAL_HOST:http://localhost:8888}/realms/${KEYCLOAK_REALM:EDDIE}/protocol/openid-connect/certs
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: ${KEYCLOAK_CLIENT:AIIDA}
            client-secret: ${KEYCLOAK_CLIENT_SECRET:REPLACE_ME}
            authorization-grant-type: authorization_code
            redirect-uri: ${AIIDA_EXTERNAL_HOST:http://localhost:8080}/login/oauth2/code/keycloak
            scope: openid
            provider: keycloak

aiida:
  installer:
    host: http://aiida-installer:8010
  mqtt:
    host: ${MQTT_EXTERNAL_HOST:tcp://localhost:1884}
  keycloak:
    account-uri: ${KEYCLOAK_EXTERNAL_HOST:http://localhost:8888}/realms/${KEYCLOAK_REALM:EDDIE}/account
    end-session-uri: ${KEYCLOAK_EXTERNAL_HOST:http://localhost:8888}/realms/${KEYCLOAK_REALM:EDDIE}/protocol/openid-connect/logout

marketplace:
  federatorUrl: http://localhost:9090/api/certificates
  keystorePath: ${KEYSTORE_PATH:aiida/src/main/resources/keystore.p12}
  keystorePassword: ${KEYSTORE_PASSWORD}:REPLACE_ME
