spring:
  datasource:
    url: jdbc:postgresql://REPLACE_ME:5433/aiida
    username: REPLACE_ME
    password: REPLACE_ME
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: 'true'
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations: 'classpath:db/aiida/migration'
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${aiida.keycloak.url.external}/realms/${aiida.keycloak.realm}
          jwk-set-uri: ${aiida.keycloak.url.internal}/realms/${aiida.keycloak.realm}/protocol/openid-connect/certs
      client:
        provider:
          keycloak:
            authorization-uri: ${aiida.keycloak.url.external}/realms/${aiida.keycloak.realm}/protocol/openid-connect/auth
            token-uri: ${aiida.keycloak.url.internal}/realms/${aiida.keycloak.realm}/protocol/openid-connect/token
            user-info-uri: ${aiida.keycloak.url.internal}/realms/${aiida.keycloak.realm}/protocol/openid-connect/userinfo
            jwk-set-uri: ${aiida.keycloak.url.internal}/realms/${aiida.keycloak.realm}/protocol/openid-connect/certs
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: ${aiida.keycloak.client}
            client-secret: ${aiida.keycloak.secret}
            authorization-grant-type: authorization_code
            redirect-uri: ${aiida.public.url}/login/oauth2/code/keycloak
            scope: openid
            provider: keycloak

aiida:
  public:
    url: ${AIIDA_EXTERNAL_HOST:http://localhost:${server.port}}
  installer:
    host: http://aiida-installer:8010
  mqtt:
    internal-host: ${MQTT_INTERNAL_HOST:tcp://localhost:1884}
    external-host: ${MQTT_EXTERNAL_HOST:tcp://localhost:1884}
    bcrypt-salt-rounds: ${MQTT_BCRYPT_SALT_ROUNDS:12}
    password: ${MQTT_PASSWORD:REPLACE_ME_WITH_SAVE_PASSWORD}
    tls-certificate-path: ${MQTT_TLS_CERTIFICATE_PATH:}
  keycloak:
    url:
      internal: ${KEYCLOAK_INTERNAL_HOST:http://localhost:8888}
      external: ${KEYCLOAK_EXTERNAL_HOST:http://localhost:8888}
    realm: ${KEYCLOAK_REALM:EDDIE}
    client: ${KEYCLOAK_CLIENT:AIIDA}
    secret: ${KEYCLOAK_CLIENT_SECRET:REPLACE_ME}
    account-uri: ${aiida.keycloak.url.external}/realms/${aiida.keycloak.realm}/account
    end-session-uri: ${aiida.keycloak.url.external}/realms/${aiida.keycloak.realm}/protocol/openid-connect/logout