services:
  timescaledb:
    image: timescale/timescaledb:latest-pg12
    environment:
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      POSTGRES_DB: aiida
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always

  aiida:
    image: ghcr.io/eddie-energy/aiida:latest
    depends_on:
      timescaledb:
        condition: service_started
      nanomq:
        condition: service_started
      keycloak:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://timescaledb:5432/aiida"
    env_file:
      - .env

  nanomq:
    image: emqx/nanomq:latest
    ports:
      - "1884:1883"
      - "8084:8083"
      - "8884:8883"
    volumes:
      - ./nanomq/nanomq_pwd.conf:/etc/nanomq_pwd.conf
      - ./nanomq/nanomq.conf:/etc/nanomq.conf

  teleinfo2mqtt:
    depends_on:
      - nanomq
    profiles:
      - teleinfo
    image: fmartinou/teleinfo2mqtt
    container_name: teleinfo2mqtt
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    env_file:
      - .env-fr-teleinfo2mqtt
    restart: always

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    ports:
      - "8888:8080"
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN_USERNAME}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_HEALTH_ENABLED: true
    volumes:
      - ./keycloak-realm.json:/opt/keycloak/data/import/keycloak-realm.json
      - ../../keycloak-eddie-theme/theme/eddie-theme:/opt/keycloak/themes/eddie-theme
    command: -v start-dev --import-realm
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "exec 3<>/dev/tcp/127.0.0.1/9000; echo -e 'GET /health/ready HTTP/1.1\r\nHost: localhost:9000\r\nConnection: close\r\n\r\n' >&3;cat <&3 | grep -q '\"status\": \"UP\"' && exit 0 || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  default:
    name: "aiida_bridge"

volumes:
  db_data: