name: aiida
services:
  timescaledb:
    image: timescale/timescaledb:latest-pg17
    ports:
      - "5433:5432"
    environment:
      EMQX_DATABASE_PASSWORD: ${EMQX_DATABASE_PASSWORD}
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      POSTGRES_DB: ${SPRING_DATASOURCE_DATABASE}
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./postgres/create-emqx-user.sql:/tmp/create-emqx-user.sql
      - ./postgres/replace-password-with-env.sh:/docker-entrypoint-initdb.d/00-replace_password_with_env.sh
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${SPRING_DATASOURCE_USERNAME} -d ${SPRING_DATASOURCE_DATABASE}'" ]
      interval: 10s
      timeout: 3s
      retries: 3

  aiida:
    image: ghcr.io/eddie-energy/aiida:latest
    build:
      dockerfile: docker/Dockerfile
      context: ../
    depends_on:
      timescaledb:
        condition: service_healthy
      emqx:
        condition: service_healthy
      keycloak:
        condition: service_healthy
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://${SPRING_DATASOURCE_HOST}:${SPRING_DATASOURCE_PORT}/${SPRING_DATASOURCE_DATABASE}
    env_file:
      - .env
      - path: .env.local
        required: false
    volumes:
      - ./svgs:/container-assets/svgs
    extra_hosts:
      - "localhost:host-gateway" # access host machine as "localhost"

  emqx:
    image: emqx/emqx:5.8.6
    depends_on:
      timescaledb:
        condition: service_healthy
    ports:
      - "1884:1883"
      - "8884:8883"
      - "18084:18083"
    environment:
      AIIDA_MQTT_PASSWORD: ${MQTT_PASSWORD}
      EMQX_AUTHENTICATION__1__DATABASE: ${SPRING_DATASOURCE_DATABASE}
      EMQX_AUTHENTICATION__1__SERVER: ${SPRING_DATASOURCE_HOST}:${SPRING_DATASOURCE_PORT}
      EMQX_AUTHENTICATION__1__PASSWORD: ${EMQX_DATABASE_PASSWORD}
      EMQX_AUTHORIZATION__SOURCES__1__DATABASE: ${SPRING_DATASOURCE_DATABASE}
      EMQX_AUTHORIZATION__SOURCES__1__SERVER: ${SPRING_DATASOURCE_HOST}:${SPRING_DATASOURCE_PORT}
      EMQX_AUTHORIZATION__SOURCES__1__PASSWORD: ${EMQX_DATABASE_PASSWORD}
    restart: always
    volumes:
      - emqx_data:/opt/emqx/data
      - ./emqx/emqx.hocon:/opt/emqx/etc/base.hocon
      - ./emqx/init-user.json:/tmp/init-user.json
      - ./emqx/replace-password-with-env.sh:/tmp/replace-password-with-env.sh
    entrypoint: [ "/bin/sh", "/tmp/replace-password-with-env.sh" ]
    healthcheck:
      test: [ "CMD", "/opt/emqx/bin/emqx", "ctl", "status" ]
      interval: 5s
      timeout: 25s
      retries: 5

  teleinfo2mqtt:
    depends_on:
      - emqx
    profiles:
      - teleinfo
    image: fmartinou/teleinfo2mqtt
    container_name: teleinfo2mqtt
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    env_file:
      - .env-fr-teleinfo2mqtt
    restart: always

  keycloak:
    image: quay.io/keycloak/keycloak:26.2.1
    ports:
      - "8889:8080"
    environment:
      KC_HOSTNAME: ${KEYCLOAK_EXTERNAL_HOST}
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_ADMIN_USERNAME}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_HEALTH_ENABLED: true
    command: -v start-dev --import-realm
    volumes:
      - keycloak_data:/opt/keycloak/data
      - ./keycloak/AIIDA-realm.json:/opt/keycloak/data/import/AIIDA-realm.json
      - ../../keycloak-eddie-theme/themes/eddie-theme:/opt/keycloak/themes/eddie-theme
      - ../../keycloak-eddie-theme/themes/aiida-theme:/opt/keycloak/themes/aiida-theme
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "exec 3<>/dev/tcp/127.0.0.1/9000; echo -e 'GET /health/ready HTTP/1.1\r\nHost: localhost:9000\r\nConnection: close\r\n\r\n' >&3;cat <&3 | grep -q '\"status\": \"UP\"' && exit 0 || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  db_data:
  emqx_data:
  keycloak_data: