name: aiida-e2e
services:
  aiida:
    container_name: aiida
    pull_policy: build
    env_file:
      - .env.e2e

  emqx:
    container_name: aiida-emqx

  keycloak:
    container_name: aiida-keycloak

networks:
  default:
    external: true
    name: "e2e-tests-network"
