name: Build Containers

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io

jobs:
  build:

    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Gradle build
        run: ./gradlew installDist
      - name: "Docker build image: EDDIE"
        run: docker build -f ./core/src/main/docker/Dockerfile -t eddie ./core
      - name: "Docker build image: EDDIE example-app"
        run: docker build -f ./examples/example-app/src/main/docker/Dockerfile -t eddie-example-app ./examples/example-app
      - name: Print some debugging information
        run: |
          echo github.repository_owner: ${{ github.repository_owner }}
          echo github.ref: ${{ github.ref }}
          echo GITHUB_RUN_ID: ${GITHUB_RUN_ID}
      # Usage of docker is done through direct commands instead of using predefined actions for these reasons:
      # - Usage of the docker command line is well documented and already understood by all developers that
      #   used docker before. Usage of a docker-related action requires additional knowledge that is seldomly present.
      # - Security tokens are not passed through an action to give less surface to supply chain attacks that might be
      #   used for stealing docker related secrets. That supply chain attack may occur in the used GitHub action or any
      #   library that is used by that action explicitly or implicitly. Especially in the Node.js/npm ecosystem that
      #   must be used by all GitHub actions, supply chain attacks became common in recent times.
      - name: ghcr.io login
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
      - name: "Docker push image: EDDIE example-app"
        run: |
          IMAGE_NAME=eddie-example-app
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/${IMAGE_NAME}
          VERSION=latest
          echo IMAGE_NAME: $IMAGE_NAME
          echo IMAGE_ID: $IMAGE_ID
          echo VERSION: $VERSION
          docker tag ${IMAGE_NAME} $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
      - name: "Docker push image: EDDIE"
        run: |
          IMAGE_NAME=eddie
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/${IMAGE_NAME}
          VERSION=latest
          echo IMAGE_NAME: $IMAGE_NAME
          echo IMAGE_ID: $IMAGE_ID
          echo VERSION: $VERSION
          docker tag ${IMAGE_NAME} $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
      - name: Post ghcr.io login
        run: rm $HOME/.docker/config.json

  build-aiida:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: aiida

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build and publish image
        run: |
          IMAGE_ID=${REGISTRY}/${{ github.repository_owner }}/${IMAGE_NAME}
          echo $IMAGE_ID
          ./gradlew --no-daemon jib --image $IMAGE_ID -Djib.to.auth.password=${{ secrets.GITHUB_TOKEN }}
