name: Build and deploy EDDIE javadocs
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    paths:
      - "**.java"
  push:
    branches:
      - main
    paths:
      - "**.java"
  workflow_dispatch:

jobs:
  docs-deploy:
    runs-on: [ linux, no-dind ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Gradle build javadocs
        run: ./gradlew allJavadoc
      - name: Deploy javadoc to webserver
        if: github.ref_name == 'main'
        uses: eddie-energy/ftp-deploy-action@main
        with:
          host: ${{ secrets.WEBSERVER_SFTP_HOST }}
          source: "./build/docs/javadoc-all/"
          destination: "/public_html/javadoc/"
          password: ${{ secrets.WEBSERVER_SFTP_PASSWORD }}
          user: ${{ secrets.WEBSERVER_SFTP_USERNAME }}
