name: Deploy EDDIE Framework docs
on:
  push:
    paths:
      - 'docs/**'
    branches:
      - main
  workflow_dispatch:

jobs:
  docs-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Gradle build framework-docs and javadocs
        run: ./gradlew pnpmBuildDocs allJavadoc
      - name: Deploy docs to webserver
        uses: SamKirkland/web-deploy@v1
        with:
          target-server: ${{ secrets.WEBSERVER_SSH_HOST }}
          remote-user: ${{ secrets.WEBSERVER_SSH_USERNAME }}
          private-ssh-key: ${{ secrets.WEBSERVER_SSH_KEY }}
          source-path: ./docs/.vitepress/dist/
          destination-path: /web/framework/
      - name: Deploy javadoc to webserver
        uses: SamKirkland/web-deploy@v1
        with:
          target-server: ${{ secrets.WEBSERVER_SSH_HOST }}
          remote-user: ${{ secrets.WEBSERVER_SSH_USERNAME }}
          private-ssh-key: ${{ secrets.WEBSERVER_SSH_KEY }}
          source-path: ./build/docs/javadoc-all/
          destination-path: /web/javadoc/
