name: Build and deploy EDDIE javadocs
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    paths:
      - "**.java"
  push:
    branches:
      - main
    paths:
      - "**.java"
  workflow_dispatch:

jobs:
  docs-deploy:
    runs-on: [ linux, external ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Gradle build javadocs
        run: ./gradlew allJavadoc
      - name: Deploy javadoc
        uses: appleboy/scp-action@7179e72a3fa4d4c33870a471708fda724fae7596
        with:
          host: ${{ secrets.EDDIE_ENERGY_SSH_HOST }}
          username: ${{ secrets.EDDIE_ENERGY_SSH_USERNAME }}
          password: ${{ secrets.EDDIE_ENERGY_SSH_PASSWORD }}
          source: "./build/docs/javadoc-all/"
          target: "/var/www/vhosts/eddie.energy/architecture.eddie.energy/javadoc/"
          strip_components: "4"
          overwrite: true
