name: Deploy EDDIE javadocs
on:
  push:
    branches:
      - main
    paths:
      - "**.java"
  workflow_dispatch:

jobs:
  docs-deploy:
    runs-on: [linux, no-dind]
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Gradle build javadocs
        run: ./gradlew allJavadoc
      - name: Deploy javadoc to webserver
        uses: ./.github/actions/sftp-deploy
        with:
          host: ${{ secrets.WEBSERVER_SFTP_HOST }}
          login_name: ${{ secrets.WEBSERVER_SFTP_USERNAME }}
          private_key: ${{ secrets.WEBSERVER_SFTP_KEY }}
          source: "./build/docs/javadoc-all/**"
          destination: "/public_html/javadoc/"
