name: Tag Docker Image with Release Tag

on:
  push:
    tags: [ release-* ]

jobs:
  build:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write
    env:
      registry: ghcr.io/eddie-energy
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Log into the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag and push existing Docker image
        run: |
          docker pull ghcr.io/eddie-energy/eddie:latest
          docker tag ghcr.io/eddie-energy/eddie:latest ghcr.io/eddie-energy/eddie:${{ steps.get_version.outputs.VERSION }}
          docker push ghcr.io/eddie-energy/eddie:${{ steps.get_version.outputs.VERSION }}
          
          docker pull ghcr.io/eddie-energy/eddie-example-app:latest
          docker tag ghcr.io/eddie-energy/eddie-example-app:latest ghcr.io/eddie-energy/eddie-example-app:${{ steps.get_version.outputs.VERSION }}
          docker push ghcr.io/eddie-energy/eddie-example-app:${{ steps.get_version.outputs.VERSION }}
          
          docker pull ghcr.io/eddie-energy/aiida:latest --platform linux/amd64
          docker tag ghcr.io/eddie-energy/aiida:latest ghcr.io/eddie-energy/aiida:${{ steps.get_version.outputs.VERSION }}-amd64
          docker push ghcr.io/eddie-energy/aiida:${{ steps.get_version.outputs.VERSION }}-amd64
          
          docker pull ghcr.io/eddie-energy/aiida:latest --platform linux/arm64
          docker tag ghcr.io/eddie-energy/aiida:latest ghcr.io/eddie-energy/aiida:${{ steps.get_version.outputs.VERSION }}-arm64
          docker push ghcr.io/eddie-energy/aiida:${{ steps.get_version.outputs.VERSION }}-arm64
          
          docker manifest create ghcr.io/eddie-energy/aiida:${{ steps.get_version.outputs.VERSION }} --amend ghcr.io/eddie-energy/aiida:${{ steps.get_version.outputs.VERSION }}-amd64 --amend ghcr.io/eddie-energy/aiida:${{ steps.get_version.outputs.VERSION }}-arm64
          docker manifest push ghcr.io/eddie-energy/aiida:${{ steps.get_version.outputs.VERSION }}
